services:
    netgen_layouts.sylius.cms.block.block_definition_handler.entity_field:
        class: Netgen\Layouts\Sylius\Cms\Block\BlockDefinition\Handler\EntityFieldHandler
        arguments:
            - "@request_stack"
        tags:
            - { name: netgen_layouts.block_definition_handler, identifier: sylius_cms_entity_field }
