services:
    netgen_layouts.sylius.cms.collection.query_type_handler.page:
        class: Netgen\Layouts\Sylius\Cms\Collection\QueryType\Handler\PageHandler
        arguments:
            - "@netgen_layouts.sylius.cms.repository.page"
            - "@sylius.context.locale"
            - "@request_stack"
        tags:
            - { name: netgen_layouts.query_type_handler, type: sylius_cms_page }

    netgen_layouts.sylius.cms.collection.query_type_handler.block:
        class: Netgen\Layouts\Sylius\Cms\Collection\QueryType\Handler\BlockHandler
        arguments:
            - "@netgen_layouts.sylius.cms.repository.block"
            - "@request_stack"
        tags:
            - { name: netgen_layouts.query_type_handler, type: sylius_cms_block }

    netgen_layouts.sylius.cms.collection.query_type_handler.media:
        class: Netgen\Layouts\Sylius\Cms\Collection\QueryType\Handler\MediaHandler
        arguments:
            - "@netgen_layouts.sylius.cms.repository.media"
            - "@sylius.context.locale"
            - "@request_stack"
        tags:
            - { name: netgen_layouts.query_type_handler, type: sylius_cms_media }

    netgen_layouts.sylius.cms.collection.query_type_handler.collection:
        class: Netgen\Layouts\Sylius\Cms\Collection\QueryType\Handler\CollectionHandler
        arguments:
            - "@netgen_layouts.sylius.cms.repository.collection"
        tags:
            - { name: netgen_layouts.query_type_handler, type: sylius_cms_collection }
