services:
    netgen_layouts.sylius.bitbag.backend.bitbag_page:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\PageBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.repository.page"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_page }

    netgen_layouts.sylius.bitbag.backend.bitbag_section:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\SectionBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.repository.section"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_section }

    netgen_layouts.sylius.bitbag.backend.bitbag_block:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\BlockBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.repository.block"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_block }

    netgen_layouts.sylius.bitbag.backend.bitbag_media:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\MediaBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.repository.media"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_media }

    netgen_layouts.sylius.bitbag.backend.frequently_asked_question:
        class: Netgen\Layouts\Sylius\BitBag\ContentBrowser\Backend\FrequentlyAskedQuestionBackend
        arguments:
            - "@netgen_layouts.sylius.bitbag.repository.frequently_asked_question"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: bitbag_frequently_asked_question }
