services:
    netgen_layouts.sylius.cms.event_listener.page_show:
        class: Netgen\Bundle\LayoutsSyliusCmsBundle\EventListener\PageShowListener
        arguments:
            - "@request_stack"
            - "@netgen_layouts.context"
        tags:
            - { name: kernel.event_subscriber }

    netgen_layouts.sylius.cms.event_listener.page_index:
        class: Netgen\Bundle\LayoutsSyliusCmsBundle\EventListener\PageIndexListener
        arguments:
            - "@netgen_layouts.sylius.cms.repository.collection"
            - "@request_stack"
            - "@netgen_layouts.context"
        tags:
            - { name: kernel.event_subscriber }
