services:
    netgen_layouts.sylius.bitbag.event_listener.bitbag.page_show:
        class: Netgen\Bundle\LayoutsSyliusBitBagBundle\EventListener\BitBag\PageShowListener
        arguments:
            - "@request_stack"
            - "@netgen_layouts.context"
        tags:
            - { name: kernel.event_subscriber }

    netgen_layouts.sylius.bitbag.event_listener.bitbag.page_index:
        class: Netgen\Bundle\LayoutsSyliusBitBagBundle\EventListener\BitBag\PageIndexListener
        arguments:
            - "@netgen_layouts.sylius.bitbag.section_repository"
            - "@sylius.context.locale"
            - "@request_stack"
            - "@netgen_layouts.context"
        tags:
            - { name: kernel.event_subscriber }
