services:
    netgen_layouts.sylius.cms.event_listener.page_show:
        class: Netgen\Bundle\LayoutsSyliusCmsBundle\EventListener\PageShowListener
        arguments:
            - "@netgen_layouts.sylius.cms.repository.page"
            - "@sylius.context.locale"
            - "@sylius.context.channel"
            - "@netgen_layouts.context"
        tags:
            - { name: kernel.event_subscriber }

    netgen_layouts.sylius.cms.event_listener.collection_show:
        class: Netgen\Bundle\LayoutsSyliusCmsBundle\EventListener\CollectionShowListener
        arguments:
            - "@netgen_layouts.sylius.cms.repository.collection"
            - "@netgen_layouts.context"
        tags:
            - { name: kernel.event_subscriber }
