services:
    netgen_layouts.sylius.cms.item.value_converter.page:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueConverter\PageValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.cms.item.value_loader.page:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueLoader\PageValueLoader
        arguments:
            - "@netgen_layouts.sylius.cms.repository.page"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: sylius_cms_page }

    netgen_layouts.sylius.cms.item.value_url_generator.page:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueUrlGenerator\PageValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: sylius_cms_page }

    netgen_layouts.sylius.cms.item.value_converter.section:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueConverter\SectionValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.cms.item.value_loader.section:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueLoader\SectionValueLoader
        arguments:
            - "@netgen_layouts.sylius.cms.repository.section"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: sylius_cms_section }

    netgen_layouts.sylius.cms.item.value_url_generator.section:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueUrlGenerator\SectionValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: sylius_cms_section }

    netgen_layouts.sylius.cms.item.value_converter.block:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueConverter\BlockValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.cms.item.value_loader.block:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueLoader\BlockValueLoader
        arguments:
            - "@netgen_layouts.sylius.cms.repository.block"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: sylius_cms_block }

    netgen_layouts.sylius.cms.item.value_url_generator.block:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueUrlGenerator\BlockValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: sylius_cms_block }

    netgen_layouts.sylius.cms.item.value_converter.media:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueConverter\MediaValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.cms.item.value_loader.media:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueLoader\MediaValueLoader
        arguments:
            - "@netgen_layouts.sylius.cms.repository.media"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: sylius_cms_media }

    netgen_layouts.sylius.cms.item.value_url_generator.media:
        class: Netgen\Layouts\Sylius\Cms\Item\ValueUrlGenerator\MediaValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: sylius_cms_media }
