services:
    netgen_layouts.sylius.cms.layout_resolver.target_type.page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetType\Page
        arguments:
            - "@netgen_layouts.sylius.cms.repository.page"
        tags:
            - { name: netgen_layouts.target_type, priority: 190 }

    netgen_layouts.sylius.cms.layout_resolver.target_type.form_mapper.page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\Form\TargetType\Mapper\PageMapper
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: sylius_cms_page }

    netgen_layouts.sylius.cms.layout_resolver.target_handler.doctrine.sylius_cms_page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetHandler\Doctrine\Page
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: sylius_cms_page }

    netgen_layouts.sylius.cms.layout_resolver.target_type.collection:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetType\Collection
        arguments:
            - "@netgen_layouts.sylius.cms.repository.collection"
        tags:
            - { name: netgen_layouts.target_type, priority: 180 }

    netgen_layouts.sylius.cms.layout_resolver.target_type.form_mapper.collection:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\Form\TargetType\Mapper\CollectionMapper
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: sylius_cms_collection }

    netgen_layouts.sylius.cms.layout_resolver.target_handler.doctrine.sylius_cms_collection:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetHandler\Doctrine\Collection
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: sylius_cms_collection }

    netgen_layouts.sylius.cms.layout_resolver.target_type.collection_page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetType\CollectionPage
        arguments:
            - "@netgen_layouts.sylius.cms.repository.collection"
        tags:
            - { name: netgen_layouts.target_type, priority: 180 }

    netgen_layouts.sylius.cms.layout_resolver.target_type.form_mapper.collection_page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\Form\TargetType\Mapper\CollectionPageMapper
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: sylius_cms_collection_page }

    netgen_layouts.sylius.cms.layout_resolver.target_handler.doctrine.sylius_cms_collection_page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetHandler\Doctrine\CollectionPage
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: sylius_cms_collection_page }
