services:
    netgen_layouts.sylius.cms.layout_resolver.target_type.page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetType\Page
        arguments:
            - "@netgen_layouts.sylius.cms.repository.page"
        tags:
            - { name: netgen_layouts.target_type, priority: 190 }

    netgen_layouts.sylius.cms.layout_resolver.target_type.form_mapper.page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\Form\TargetType\Mapper\PageMapper
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: sylius_cms_page }

    netgen_layouts.sylius.cms.layout_resolver.target_handler.doctrine.sylius_cms_page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetHandler\Doctrine\Page
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: sylius_cms_page }

    netgen_layouts.sylius.cms.layout_resolver.target_type.section:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetType\Section
        arguments:
            - "@netgen_layouts.sylius.cms.repository.section"
        tags:
            - { name: netgen_layouts.target_type, priority: 180 }

    netgen_layouts.sylius.cms.layout_resolver.target_type.form_mapper.section:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\Form\TargetType\Mapper\SectionMapper
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: sylius_cms_section }

    netgen_layouts.sylius.cms.layout_resolver.target_handler.doctrine.sylius_cms_section:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetHandler\Doctrine\Section
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: sylius_cms_section }

    netgen_layouts.sylius.cms.layout_resolver.target_type.section_page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetType\SectionPage
        arguments:
            - "@netgen_layouts.sylius.cms.repository.section"
        tags:
            - { name: netgen_layouts.target_type, priority: 180 }

    netgen_layouts.sylius.cms.layout_resolver.target_type.form_mapper.section_page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\Form\TargetType\Mapper\SectionPageMapper
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: sylius_cms_section_page }

    netgen_layouts.sylius.cms.layout_resolver.target_handler.doctrine.sylius_cms_section_page:
        class: Netgen\Layouts\Sylius\Cms\Layout\Resolver\TargetHandler\Doctrine\SectionPage
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: sylius_cms_section_page }
