services:
    netgen_layouts.sylius.cms.parameters.parameter_type.collection:
        class: Netgen\Layouts\Sylius\Cms\Parameters\ParameterType\CollectionType
        arguments:
            - "@netgen_layouts.sylius.cms.repository.collection"
        tags:
            - { name: netgen_layouts.parameter_type }

    netgen_layouts.sylius.cms.parameters.form_mapper.collection:
        class: Netgen\Layouts\Sylius\Cms\Parameters\Form\Mapper\CollectionMapper
        tags:
            - { name: netgen_layouts.parameter_type.form_mapper, parameter_type: sylius_cms_collection }
