services:
    netgen_layouts.sylius.cms.repository.page:
        class: Netgen\Layouts\Sylius\Cms\Repository\PageRepository
        parent: sylius_cms.repository.page

    netgen_layouts.sylius.cms.repository.collection:
        class: Netgen\Layouts\Sylius\Cms\Repository\CollectionRepository
        parent: sylius_cms.repository.collection

    netgen_layouts.sylius.cms.repository.block:
        class: Netgen\Layouts\Sylius\Cms\Repository\BlockRepository
        parent: sylius_cms.repository.block

    netgen_layouts.sylius.cms.repository.media:
        class: Netgen\Layouts\Sylius\Cms\Repository\MediaRepository
        parent: sylius_cms.repository.media
