services:
    netgen_layouts.sylius.cms.repository.page:
        class: Netgen\Layouts\Sylius\Cms\Repository\PageRepository
        parent: bitbag_sylius_cms_plugin.repository.page

    netgen_layouts.sylius.cms.repository.section:
        class: Netgen\Layouts\Sylius\Cms\Repository\SectionRepository
        parent: bitbag_sylius_cms_plugin.repository.section

    netgen_layouts.sylius.cms.repository.block:
        class: Netgen\Layouts\Sylius\Cms\Repository\BlockRepository
        parent: bitbag_sylius_cms_plugin.repository.block

    netgen_layouts.sylius.cms.repository.media:
        class: Netgen\Layouts\Sylius\Cms\Repository\MediaRepository
        parent: bitbag_sylius_cms_plugin.repository.media
