services:
    netgen_layouts.sylius.cms.validator.page:
        class: Netgen\Layouts\Sylius\Cms\Validator\PageValidator
        arguments:
            - "@netgen_layouts.sylius.cms.repository.page"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_cms_page }

    netgen_layouts.sylius.cms.validator.collection:
        class: Netgen\Layouts\Sylius\Cms\Validator\CollectionValidator
        arguments:
            - "@netgen_layouts.sylius.cms.repository.collection"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_cms_collection }
