view:
    block_view:
        default:
            sylius_cms_entity_field\string:
                template: "@nglayouts/block/sylius_cms_entity_field/string.html.twig"
                match:
                    block\definition: sylius_cms_entity_field
                    block\view_type: string
            sylius_cms_entity_field\content:
                template: "@nglayouts/block/sylius_cms_entity_field/content.html.twig"
                match:
                    block\definition: sylius_cms_entity_field
                    block\view_type: content
            sylius_cms_entity_field\number:
                template: "@nglayouts/block/sylius_cms_entity_field/number.html.twig"
                match:
                    block\definition: sylius_cms_entity_field
                    block\view_type: number
            sylius_cms_entity_field\datetime:
                template: "@nglayouts/block/sylius_cms_entity_field/datetime.html.twig"
                match:
                    block\definition: sylius_cms_entity_field
                    block\view_type: datetime
            sylius_cms_entity_field\media:
                template: "@nglayouts/block/sylius_cms_entity_field/media.html.twig"
                match:
                    block\definition: sylius_cms_entity_field
                    block\view_type: media
        app:
            sylius_cms_entity_field:
                template: "@nglayouts_admin/app/block/sylius_cms_entity_field.html.twig"
                match:
                    block\definition: sylius_cms_entity_field
