view:
    item_view:
        default:
            sylius_cms_page:
                template: "@nglayouts/item/sylius_cms_page.html.twig"
                match:
                    item\value_type: sylius_cms_page
            sylius_cms_collection:
                template: "@nglayouts/item/sylius_cms_collection.html.twig"
                match:
                    item\value_type: sylius_cms_collection
            sylius_cms_block:
                template: "@nglayouts/item/sylius_cms_block.html.twig"
                match:
                    item\value_type: sylius_cms_block
            sylius_cms_media:
                template: "@nglayouts/item/sylius_cms_media.html.twig"
                match:
                    item\value_type: sylius_cms_media
        ajax:
            sylius_cms_page:
                template: "@nglayouts/item/sylius_cms_page.html.twig"
                match:
                    item\value_type: sylius_cms_page
            sylius_cms_collection:
                template: "@nglayouts/item/sylius_cms_collection.html.twig"
                match:
                    item\value_type: sylius_cms_collection
            sylius_cms_block:
                template: "@nglayouts/item/sylius_cms_block.html.twig"
                match:
                    item\value_type: sylius_cms_block
            sylius_cms_media:
                template: "@nglayouts/item/sylius_cms_media.html.twig"
                match:
                    item\value_type: sylius_cms_media
        app:
            sylius_cms_page:
                template: "@nglayouts_admin/app/item/sylius_cms_page.html.twig"
                match:
                    item\value_type: sylius_cms_page
            sylius_cms_collection:
                template: "@nglayouts_admin/app/item/sylius_cms_collection.html.twig"
                match:
                    item\value_type: sylius_cms_collection
            sylius_cms_block:
                template: "@nglayouts_admin/app/item/sylius_cms_block.html.twig"
                match:
                    item\value_type: sylius_cms_block
            sylius_cms_media:
                template: "@nglayouts_admin/app/item/sylius_cms_media.html.twig"
                match:
                    item\value_type: sylius_cms_media
