view:
    item_view:
        default:
            sylius_cms_page:
                template: "@nglayouts/item/sylius_cms_page.html.twig"
                match:
                    item\value_type: sylius_cms_page
            sylius_cms_section:
                template: "@nglayouts/item/sylius_cms_section.html.twig"
                match:
                    item\value_type: sylius_cms_section
            sylius_cms_block:
                template: "@nglayouts/item/sylius_cms_block.html.twig"
                match:
                    item\value_type: sylius_cms_block
            sylius_cms_media:
                template: "@nglayouts/item/sylius_cms_media.html.twig"
                match:
                    item\value_type: sylius_cms_media
            sylius_cms_frequently_asked_question:
                template: "@nglayouts/item/sylius_cms_frequently_asked_question.html.twig"
                match:
                    item\value_type: sylius_cms_frequently_asked_question
        ajax:
            sylius_cms_page:
                template: "@nglayouts/item/sylius_cms_page.html.twig"
                match:
                    item\value_type: sylius_cms_page
            sylius_cms_section:
                template: "@nglayouts/item/sylius_cms_section.html.twig"
                match:
                    item\value_type: sylius_cms_section
            sylius_cms_block:
                template: "@nglayouts/item/sylius_cms_block.html.twig"
                match:
                    item\value_type: sylius_cms_block
            sylius_cms_media:
                template: "@nglayouts/item/sylius_cms_media.html.twig"
                match:
                    item\value_type: sylius_cms_media
            sylius_cms_frequently_asked_question:
                template: "@nglayouts/item/sylius_cms_frequently_asked_question.html.twig"
                match:
                    item\value_type: sylius_cms_frequently_asked_question
        app:
            sylius_cms_page:
                template: "@nglayouts_admin/app/item/sylius_cms_page.html.twig"
                match:
                    item\value_type: sylius_cms_page
            sylius_cms_section:
                template: "@nglayouts_admin/app/item/sylius_cms_section.html.twig"
                match:
                    item\value_type: sylius_cms_section
            sylius_cms_block:
                template: "@nglayouts_admin/app/item/sylius_cms_block.html.twig"
                match:
                    item\value_type: sylius_cms_block
            sylius_cms_media:
                template: "@nglayouts_admin/app/item/sylius_cms_media.html.twig"
                match:
                    item\value_type: sylius_cms_media
            sylius_cms_frequently_asked_question:
                template: "@nglayouts_admin/app/item/sylius_cms_frequently_asked_question.html.twig"
                match:
                    item\value_type: sylius_cms_frequently_asked_question
