services:
    netgen_layouts.sylius.cms.browser.backend.page:
        class: Netgen\Layouts\Sylius\Cms\Browser\Backend\PageBackend
        arguments:
            - "@netgen_layouts.sylius.cms.repository.page"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: sylius_cms_page }

    netgen_layouts.sylius.cms.browser.backend.section:
        class: Netgen\Layouts\Sylius\Cms\Browser\Backend\SectionBackend
        arguments:
            - "@netgen_layouts.sylius.cms.repository.section"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: sylius_cms_section }

    netgen_layouts.sylius.cms.browser.backend.block:
        class: Netgen\Layouts\Sylius\Cms\Browser\Backend\BlockBackend
        arguments:
            - "@netgen_layouts.sylius.cms.repository.block"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: sylius_cms_block }

    netgen_layouts.sylius.cms.browser.backend.media:
        class: Netgen\Layouts\Sylius\Cms\Browser\Backend\MediaBackend
        arguments:
            - "@netgen_layouts.sylius.cms.repository.media"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: sylius_cms_media }

    netgen_layouts.sylius.cms.browser.column_provider.page.code:
        class: Netgen\Layouts\Sylius\Cms\Browser\ColumnProvider\Page\Code
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: sylius_cms_page\code }

    netgen_layouts.sylius.cms.browser.column_provider.page.slug:
        class: Netgen\Layouts\Sylius\Cms\Browser\ColumnProvider\Page\Slug
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: sylius_cms_page\slug }

    netgen_layouts.sylius.cms.browser.column_provider.section.code:
        class: Netgen\Layouts\Sylius\Cms\Browser\ColumnProvider\Section\Code
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: sylius_cms_section\code }

    netgen_layouts.sylius.cms.browser.column_provider.block.code:
        class: Netgen\Layouts\Sylius\Cms\Browser\ColumnProvider\Block\Code
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: sylius_cms_block\code }

    netgen_layouts.sylius.cms.browser.column_provider.media.code:
        class: Netgen\Layouts\Sylius\Cms\Browser\ColumnProvider\Media\Code
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: sylius_cms_media\code }

    netgen_layouts.sylius.cms.browser.column_provider.media.type:
        class: Netgen\Layouts\Sylius\Cms\Browser\ColumnProvider\Media\Type
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: sylius_cms_media\type }

    netgen_layouts.sylius.cms.browser.column_provider.media.mime_type:
        class: Netgen\Layouts\Sylius\Cms\Browser\ColumnProvider\Media\MimeType
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: sylius_cms_media\mime_type }
