block_definitions:
    sylius_cms_entity_field:
        name: 'Sylius CMS entity field'
        icon: '/bundles/netgenlayoutssyliuscms/icons/block/sylius_cms_entity_field.svg'
        view_types:
            string:
                name: 'String'
                valid_parameters:
                    - 'field_identifier'
                    - 'html_element'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            content:
                name: 'Content'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            content_elements:
                name: 'Content elements'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            number:
                name: 'Number'
                valid_parameters:
                    - 'field_identifier'
                    - 'html_element'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            datetime:
                name: 'Date & time'
                valid_parameters:
                    - 'field_identifier'
                    - 'html_element'
                    - 'datetime_format'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            media:
                name: 'Media'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
