query_types:
    sylius_cms_page:
        name: 'Sylius CMS page'
    sylius_cms_block:
        name: 'Sylius CMS block'
    sylius_cms_media:
        name: 'Sylius CMS media'
    sylius_cms_collection:
        name: 'Sylius CMS collection'
