query_types:
    sylius_cms_page:
        name: 'Sylius CMS page'
    sylius_cms_block:
        name: 'Sylius CMS block'
    sylius_cms_media:
        name: 'Sylius CMS media'
    sylius_cms_section:
        name: 'Sylius CMS section'
    sylius_cms_frequently_asked_question:
        name: 'Sylius CMS frequently asked question'
